### PR TITLE
Modernize plugin

### PR DESCRIPTION
**Pull request by Kagami**
Hello.

I slightly modernized the plugin: fixed deps and some minor flaws. Hope you don't mind the changes.

### CODE REVIEW

**Comment by Kagami** [comment]
Hey @gabegorelick.
Please let me know if there is something you don't like in the PR. Sorry for the rush.

**Comment by Kagami** [comment]
Thanks!

**Comment by Kagami** [comment]
Could you please publish 0.4.5 to npm?

**Comment by gabegorelick** [comment]
I'm working on publishing 1.0.0 now. It will break with po2json versioning, but since that hasn't had a new version in 2+ years, I think it's OK.

Should be published soon after I clean up a few more things.

**Comment by gabegorelick** [comment]
@Kagami v1.0.0 has been published. Let me know if you have any issues.

**Comment by Kagami** [comment]
Everything is fine. Thank you.

**Pull request closed without merging**
